version: "3.8"

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: usertest
      MYSQL_USER: echu
      MYSQL_PASSWORD: echu1234
    ports:
      - 3306:3306
    # volumes:
    #   - ./data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
